twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes: ['@TalesFromADevFlowbite/form/default.html.twig']

when@test:
    twig:
        strict_variables: true